[context.production]
  publish = "build/"

[context.production.environment]
  REACT_APP_ENV = "prd"
  REACT_APP_AUTH0_REDIRECT_URI = "https://coordinator.kidsfirstdrc.org/callback"
  REACT_APP_AUTH0_LOGOUT_URI = "https://coordinator.kidsfirstdrc.org/logout"


[context.master]
  command = "yarn build"

[context.master.environment]
  REACT_APP_ENV = "qa"
  REACT_APP_AUTH0_REDIRECT_URI = "https://kf-release-coordinator-netlify.kidsfirstdrc.org/callback"
  REACT_APP_COORDINATOR_API = "https://kf-release-coord-qa.kidsfirstdrc.org"
  REACT_APP_REPORTS_API = "https://kf-task-release-reports-qa.kidsfirstdrc.org"
  REACT_APP_EGO_API = "https://ego-dev.kids-first.io"


[context.deploy-preview]
  publish = "build/"
  command = "REACT_APP_AUTH0_REDIRECT_URI=$DEPLOY_PRIME_URL/callback REACT_APP_AUTH0_LOGOUT_REDIRECT_URI=$DEPLOY_PRIME_URL/logout yarn build"

[context.deploy-preview.environment]
  REACT_APP_ENV = "dev"
  REACT_APP_COORDINATOR_API = "https://kf-release-coord-dev.kidsfirstdrc.org"

[context.branch-deploy]
  publish = "build/"
  command = "REACT_APP_AUTH0_REDIRECT_URI=$DEPLOY_PRIME_URL/callback REACT_APP_AUTH0_LOGOUT_REDIRECT_URI=$DEPLOY_PRIME_URL/logout yarn build"

[context.branch-deploy.environment]
  REACT_APP_ENV = "dev"
  REACT_APP_COORDINATOR_API = "https://kf-release-coord-dev.kidsfirstdrc.org"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
